- name: Add remi repo
  yum_repository:
    file: remi
    name: remi
    description: Remi's RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/remi/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php55 repo
  yum_repository:
    file: remi
    name: remi-php55
    description: Remi's PHP 5.5 RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/php55/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php56 repo
  yum_repository:
    file: remi
    name: remi-php56
    description: Remi's PHP 5.6 RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/php56/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-test repo
  yum_repository:
    file: remi
    name: remi-test
    description: Remi's test RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/test/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-debuginfo repo
  yum_repository:
    file: remi
    name: remi-debuginfo
    description: Remi's RPM repository for Enterprise Linux 6 - $basearch - debuginfo
    mirrorlist: "{{ remi_repourl }}/6/debug-remi/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php55-debuginfo repo
  yum_repository:
    file: remi
    name: remi-php55-debuginfo
    description: Remi's PHP 5.5 RPM repository for Enterprise Linux 6 - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/6/debug-php55/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php56-debuginfo repo
  yum_repository:
    file: remi
    name: remi-php56-debuginfo
    description: Remi's PHP 5.6 RPM repository for Enterprise Linux 6 - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/6/debug-php56/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-test-debuginfo repo
  yum_repository:
    file: remi
    name: remi-test-debuginfo
    description: Remi's test RPM repository for Enterprise Linux 6 - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/6/debug-php56/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-safe repo
  yum_repository:
    file: remi-safe
    name: remi-safe
    description: Safe Remi's RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/safe/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php70 repo
  yum_repository:
    file: remi-php70
    name: remi-php70
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/php70/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no
    priority: 1

- name: Add remi-php70-debuginfo repo
  yum_repository:
    file: remi-php70
    name: remi-php70-debuginfo
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux 6 - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/6/debug-php70/$basearch/"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php70-test repo
  yum_repository:
    file: remi-php70
    name: remi-php70-test
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux 6 - $basearch
    mirrorlist: "{{ remi_repourl }}/6/test70/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php70-test-debuginfo repo
  yum_repository:
    file: remi-php70
    name: remi-php70-test-debuginfo
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux 6 - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/6/debug-test70/$basearch/"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no
