# - include: "{{ ansible_distribution }}.yml"

- name: include vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Add remi repo
  yum_repository:
    file: remi
    name: remi
    description: Remi's RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/remi/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php55 repo
  yum_repository:
    file: remi
    name: remi-php55
    description: Remi's PHP 5.5 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/php55/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php56 repo
  yum_repository:
    file: remi
    name: remi-php56
    description: Remi's PHP 5.6 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/php56/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-test repo
  yum_repository:
    file: remi
    name: remi-test
    description: Remi's test RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/test/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-debuginfo repo
  yum_repository:
    file: remi
    name: remi-debuginfo
    description: Remi's RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch - debuginfo
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/debug-remi/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php55-debuginfo repo
  yum_repository:
    file: remi
    name: remi-php55-debuginfo
    description: Remi's PHP 5.5 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/{{ remi_repo_ver }}/debug-php55/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php56-debuginfo repo
  yum_repository:
    file: remi
    name: remi-php56-debuginfo
    description: Remi's PHP 5.6 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/{{ remi_repo_ver }}/debug-php56/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-test-debuginfo repo
  yum_repository:
    file: remi
    name: remi-test-debuginfo
    description: Remi's test RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/{{ remi_repo_ver }}/debug-php56/$basearch"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-safe repo
  yum_repository:
    file: remi-safe
    name: remi-safe
    description: Safe Remi's RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/safe/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php70 repo
  yum_repository:
    file: remi-php70
    name: remi-php70
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/php70/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no
    priority: 1

- name: Add remi-php70-debuginfo repo
  yum_repository:
    file: remi-php70
    name: remi-php70-debuginfo
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/{{ remi_repo_ver }}/debug-php70/$basearch/"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php70-test repo
  yum_repository:
    file: remi-php70
    name: remi-php70-test
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch
    mirrorlist: "{{ remi_repourl }}/{{ remi_repo_ver }}/test70/mirror"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: Add remi-php70-test-debuginfo repo
  yum_repository:
    file: remi-php70
    name: remi-php70-test-debuginfo
    description: Remi's PHP 7.0 RPM repository for Enterprise Linux {{ remi_repo_ver }} - $basearch - debuginfo
    baseurl: "{{ remi_repourl }}/{{ remi_repo_ver }}/debug-test70/$basearch/"
    gpgkey: "{{ remi_gpgkey }}"
    gpgcheck: yes
    enabled: no

- name: install libwebp from epel
  yum: name=libwebp disablerepo=* enablerepo=epel

- name: install php-fpm
  yum: name={{ item }} state=present enablerepo=remi,remi-safe,remi-php70
  with_items:
    - php
    - php-fpm
    - php-mcrypt
    - php-cli
    - php-common
    - php-devel
    - php-mbstring
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pear
    - php-pecl-apcu
    - php-process
    - php-xml
    - php-gd

- name: copy /etc/php-fpm.d/
  copy: src=etc/php-fpm.d/ dest=/etc/php-fpm.d/ backup=yes
  notify: restart php-fpm

- name: start php-fpm
  service: name=php-fpm state=started enabled=yes

- name: copy /etc/nginx/default.d/
  copy: src=etc/nginx/default.d/ dest=/etc/nginx/default.d/ backup=yes
  notify: restart nginx

## Common Conifgration ( CloudWatch Logs & Datadog Integration & logrotate )

- name: copy {{ awslogs_config_dir_path }}config
  copy: src=etc/awslogs/config/ dest={{ awslogs_config_dir_path }}config/ backup=yes
  notify: restart awslogs agent

- name: copy /etc/dd-agent/
  copy: src=etc/dd-agent/ dest=/etc/dd-agent/ backup=yes
  when: datadog == true
  notify: restart datadog-agent

- name: copy /etc/logrotate.d/
  copy: src=etc/logrotate.d/ dest=/etc/logrotate.d/
