- name: install php-fpm
  yum: name=php-fpm
- name: copy php-fpm conf
  copy: src=etc/ dest=/etc/ backup=yes
- name: start php-fpm
  service: name=php-fpm state=started enabled=yes

- name: copy /etc/awslogs/config/
  copy: src=etc/awslogs/config/ dest=/etc/awslogs/config/
- name: restart awslogs agent
  service: name=awslogs state=restarted enabled=yes
