- name: remi Install
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

- replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - remi.repo
    - remi-php70.repo
    - remi-safe.repo

- name: priority modifyed to remi-php70
  copy: src=etc/yum.repos.d/remi-php70.repo dest=/etc/yum.repos.d/remi-php70.repo owner=root group=root mode=0644

#- name: priority modifyed to remi-php70
#  yum_repository:
#    name: remi-php70
#    priority: 1

- name: install php-fpm
  yum: name={{ item }} state=latest enablerepo=remi-php70,remi
  with_items:
    - php
    - php-fpm
    - php-mcrypt
    - php-cli
    - php-common
    - php-devel
    - php-mbstring
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pear
    - php-pecl-apcu
    - php-process
    - php-xml
    - php-gd

- name: copy /etc/php-fpm.d/
  copy: src=etc/php-fpm.d/ dest=/etc/php-fpm.d/ backup=yes
  notify: restart php-fpm

- name: start php-fpm
  service: name=php-fpm state=started enabled=yes

- name: copy /etc/nginx/default.d/
  copy: src=etc/nginx/default.d/ dest=/etc/nginx/default.d/ backup=yes
  notify: restart nginx

## Common Conifgration ( CloudWatch Logs & Datadog Integration & logrotate )
- name: copy /etc/awslogs/config/
  copy: src=etc/awslogs/config/ dest=/etc/awslogs/config/ backup=yes
  notify: restart awslogs agent

- name: copy /etc/etc/dd-agent/
  copy: src=etc/dd-agent/ dest=/etc/dd-agent/ backup=yes
  when: datadog == true
  notify: restart datadog-agent

- name: copy /etc/logrotate.d/
  copy: src=/etc/logrotate.d/ dest=/etc/logrotate.d/
