- include: centos7-php54.ymli
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7
#  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7 and {{ php }} == "54"

- include: amazon-linux-php53.yml
  when: ansible_distribution == 'Amazon'
#  when: ansible_distribution == 'Amazon' and {{ php }} == "53"

- name: check exists PHP Composer
  stat: path="/usr/local/bin/composer"
  register: check_composer_file

- name: Install PHP Composer
  shell: |
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
  when: not check_composer_file.stat.exists
