- name: include vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
  
- include: epel.yml
- include: command.yml
- include: aws.yml
- include: initialize.yml
